import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/award.module.css'


export default function Award(){

    return(
        <div className={styles.container}>
            <Head>
                <title>Kevin Tanuwijaya</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <nav className={styles.nav}>
                    <div>
                    <span className={styles.navtitle}>
                        K
                    </span>
                    </div>
                    <div className={styles.navitems}>
                        <a href='/' className={styles.nav_item}>
                            <span>Home</span>
                        </a>
                        <a href='/award' className={styles.nav_item}>
                            <span>Award</span>
                        </a>
                    </div>
                </nav>
            </header>

            <main className={styles.main}>
                <div className={styles.main_top_section}>
                    <div className={styles.main_intro}>
                        <div className={styles.main_intro_detail}>
                            <span className={styles.main_intro_name}>KEVIN</span>
                            <br></br>
                            <span className={styles.main_intro_name}>TANUWIJAYA</span>
                            <div className={styles.main_intro_categories}>
                                <span className={styles.main_intro_categorie_item}>Computer Science</span>
                                <span className={styles.main_intro_categorie_item}>Software Engineer</span>
                            </div>
                            <a href='https://drive.google.com/file/d/14eWqzdXuqkjdFEZsfykyQzWphezPfdfr/view?usp=sharing' className={styles.link_remove_decoration}>
                            <div className={styles.main_intro_buttons}>
                                <button className={styles.main_into_resume}>Download Resume</button>
                            </div>
                            </a>
                        </div>
                        <div className={styles.main_intro_picture}>
                            <img src='assets/photo.png' />
                        </div>
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <div className={styles.footericon}>
                    <a href='https://www.linkedin.com/in/kevin-tanuwijaya-23a2771a3/'>
                    <i class="bi bi-linkedin" style={{fontSize:30,color:'white'}} ></i>
                    </a>
                    <a href='https://github.com/kevintanuwijaya'>
                    <i class="bi bi-github" style={{fontSize:30,color:'white'}}></i>
                    </a>
                    <a href='https://www.facebook.com/kevin.tanuwijaya.984'>
                    <i class="bi bi-facebook" style={{fontSize:30,color:'white'}}></i>
                    </a>
                    <a href='https://wa.me/6282295267506'>
                    <i class="bi bi-whatsapp" style={{fontSize:30,color:'white'}}></i>
                    </a>
                </div>
                <span>©2021 Kevin Tanuwijaya</span>
            </footer>
        </div>
    )

}